# Custom Dockerfile for tiskel/openstreetmap
# pelias-wof-admin-lookup is pulled from GitHub by npm install
# (see package.json: "pelias-wof-admin-lookup": "github:dominiktiskel/wof-admin-lookup#custom")
# Build context: openstreetmap/ directory

FROM pelias/baseimage

RUN apt-get update && apt-get install -y bzip2 unzip && rm -rf /var/lib/apt/lists/*

ENV WORKDIR=/code/pelias/openstreetmap
WORKDIR ${WORKDIR}

COPY ./package.json ${WORKDIR}
RUN npm install

ADD . ${WORKDIR}

RUN find . -type f -name "*.sh" -exec sed -i 's/\r$//' {} \; && \
    chmod +x ${WORKDIR}/bin/*

USER pelias

